// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viwrhnkkojgkclwnsxdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpd3Jobmtrb2pna2Nsd25zeGRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwOTIwNzUsImV4cCI6MjA1MjY2ODA3NX0.5lTe-wpjiUbGLanMchnCS75h5x8DGynIc6UIxnCCQPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);